// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
        ElRadioButton: typeof import('element-plus/es')['ElRadioButton'];
        ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
        HelloWorld默认的: typeof import('./src/components/HelloWorld默认的.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        UsePinia: typeof import('./src/components/usePinia.vue')['default'];
    }
}
